#!/usr/bin/env node

const fs = require("fs");
const jsonschema2mk = require("jsonschema2mk");
const options = require('minimist')(process.argv.slice(2));

options.level = 1;

var jsm = new jsonschema2mk(options);
require("./js2mk_multiple_schema.js")(jsm.data, jsm);

console.log("Writing README.md")

var readme = jsm.generate(jsm.data);

fs.writeFileSync("README.md", readme);
