#!/usr/bin/env node

const exec = require("child_process").spawnSync;
const argv = require('minimist')(process.argv.slice(2));
const fse = require('fs-extra');

var newname = argv._[0];
if (typeof newname !== "string" || newname === "") {
	console.info("Usage: prog NEWNAME");
	process.exit(2);
}

var baserepo = "git@github.com:osiota/base-repo-osiota-app.git";
var basedir = __dirname;

exec("git", ["clone", baserepo, newname]);
process.chdir(newname);

exec("git", ["remote", "remove", "origin"]);

//cp "${SCRIPTDIR}/template"/* .
fse.copySync(basedir + "/template", "./", { overwrite: true }, function (err) {
	if (err) {
		console.error(err);
	}
});

exec(__dirname + "/adapt-package-and-schema");
//"${SCRIPTDIR}/adapt-package-and-schema"

